// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed_follow.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one
WITH feed_follow_insert AS (
    INSERT INTO feed_follows (id, created_at, updated_at, user_id, feed_id)
    VALUES (
        $1,
        $2,
        $3,
        $4,
        $5
    )
    RETURNING id, created_at, updated_at, user_id, feed_id
)
SELECT 
    feed_follow_insert.id, feed_follow_insert.created_at, feed_follow_insert.updated_at, feed_follow_insert.user_id, feed_follow_insert.feed_id,
    users.name AS user , 
    feeds.name AS feed
FROM  feed_follow_insert
INNER JOIN users
ON feed_follow_insert.user_id = users.id
INNER JOIN feeds
ON feed_follow_insert.feed_id = feeds.id
`

type CreateFeedFollowParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

type CreateFeedFollowRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
	User      string
	Feed      string
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (CreateFeedFollowRow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.FeedID,
	)
	var i CreateFeedFollowRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
		&i.User,
		&i.Feed,
	)
	return i, err
}

const deleteFeedFollowById = `-- name: DeleteFeedFollowById :exec
DELETE FROM  feed_follows
WHERE user_id = $1 AND feed_id = $2
`

type DeleteFeedFollowByIdParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) DeleteFeedFollowById(ctx context.Context, arg DeleteFeedFollowByIdParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeedFollowById, arg.UserID, arg.FeedID)
	return err
}

const getFeedFollowByUser = `-- name: GetFeedFollowByUser :many
SELECT 
    feed_follows.id, feed_follows.created_at, feed_follows.updated_at, feed_follows.user_id, feed_follows.feed_id,
    users.name AS user, 
    feeds.name AS feed
FROM  feed_follows
INNER JOIN users
ON feed_follows.user_id = users.id
INNER JOIN feeds
ON feed_follows.feed_id = feeds.id
WHERE users.id = $1
`

type GetFeedFollowByUserRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
	User      string
	Feed      string
}

func (q *Queries) GetFeedFollowByUser(ctx context.Context, id uuid.UUID) ([]GetFeedFollowByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedFollowByUser, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedFollowByUserRow
	for rows.Next() {
		var i GetFeedFollowByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
			&i.User,
			&i.Feed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
